#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
xrdb $HOME/.Xresources &
$HOME/.config/polybar/launch.sh &
feh --bg-fill $HOME/Downloads/daniel_mountains.jpg &

bspc monitor -d TERM WEB DISC MP3 DOC MISC

bspc config border_width		0
bspc config window_gap			10

bspc config split_ratio			0.51
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true

bspc rule -a Gimp			desktop='^8' state=floating follow=on
bspc rule -a Chromium			desktop='^2'
bspc rule -a mplayer2			state=floating
bspc rule -a Zathura			desktop='^5'state=tiled follow=on focus=on
bspc rule -a Screenkey			manage=off
